/// Flutter icons SportIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SportIcons
///      fonts:
///       - asset: fonts/SportIcons.ttf
///
///
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

import 'package:flutter/widgets.dart';

class SportIcons {
  static const _kFontFam = 'SportIcons';
  static const String? _kFontPkg = null;

  static const IconData boxing_shorts =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_guard =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg_taping =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rugby_helmet =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_surfing =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cap =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cycling_helmet =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket_helmet =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biking_helmet =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball_helmet =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swim_fin =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_skating_shoe =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skating =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_shoe =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_shoe =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rafting_rows =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton_cork =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_ball =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safety_life_guare =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_glass =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing_glass =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing_stick =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipping =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rugby_ball =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_water_bottle =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowball_pins =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squash_bats =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball_bat_ball =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming_glass =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archery_bow_arrow =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javelin =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fencing =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hurdles =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skateboarding =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scuba_mouthpiece =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running_marathon =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData american_football =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_lifting =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball_shot =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shot_put =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing2 =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_hockey =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skating2 =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_jumping =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_skiing =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golfing =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mud_riding =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shooting =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData still_rings_gymnastics =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paragliding =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_jump =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watergliding =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_polo =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cycling =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_golf =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pommel_horse_gymnastics =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pommel_horse_gymnastics2 =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_jump2 =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floor_exercise_gymnastics =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData river_rafting =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer_throw =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData artistic_gymnastics =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uneven_bars =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_basket_ball =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain_climbing =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abseiling =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diving =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figure_skating =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_cricket =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man_with_olympic_torch =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taekwondo =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_watch =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing_gloves =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing_stage =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing_tapping =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sand_bag =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData punching_balls =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boomerang =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_football =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_baseball =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_rugby =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_volleyball =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprinting =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_kick =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kunfu_kick =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_tennis =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket_catch =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_volleyball =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_bowling =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archery =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball2 =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming2 =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis2 =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball_ball =
      IconData(0xf433, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_ball =
      IconData(0xf434, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowling_ball =
      IconData(0xf436, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell =
      IconData(0xf44b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_ball =
      IconData(0xf44e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf_ball =
      IconData(0xf450, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_puck =
      IconData(0xf453, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quidditch =
      IconData(0xf458, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis3 =
      IconData(0xf45d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_astronaut =
      IconData(0xf4fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static IconData? getIconByString(String? value) {
    switch (value) {
      case "boxing_shorts":
        return boxing_shorts;
      case "face_guard":
        return face_guard;
      case "leg_taping":
        return leg_taping;
      case "rugby_helmet":
        return rugby_helmet;
      case "water_surfing":
        return water_surfing;
      case "cap":
        return cap;
      case "baseball":
        return baseball;
      case "basketball":
        return basketball;
      case "cycling_helmet":
        return cycling_helmet;
      case "cricket_helmet":
        return cricket_helmet;
      case "bicycle":
        return bicycle;
      case "biking_helmet":
        return biking_helmet;
      case "baseball_helmet":
        return baseball_helmet;
      case "swim_fin":
        return swim_fin;
      case "ice_skating_shoe":
        return ice_skating_shoe;
      case "shoe":
        return shoe;
      case "skating":
        return skating;
      case "sports_shoe":
        return sports_shoe;
      case "football_shoe":
        return football_shoe;
      case "cricket":
        return cricket;
      case "rafting_rows":
        return rafting_rows;
      case "badminton_cork":
        return badminton_cork;
      case "snow_ball":
        return snow_ball;
      case "safety_life_guare":
        return safety_life_guare;
      case "football":
        return football;
      case "sports_glass":
        return sports_glass;
      case "skiing_glass":
        return skiing_glass;
      case "skiing_stick":
        return skiing_stick;
      case "skipping":
        return skipping;
      case "rugby_ball":
        return rugby_ball;
      case "volleyball":
        return volleyball;
      case "sports_water_bottle":
        return sports_water_bottle;
      case "snowball_pins":
        return snowball_pins;
      case "table_tennis":
        return table_tennis;
      case "squash_bats":
        return squash_bats;
      case "baseball_bat_ball":
        return baseball_bat_ball;
      case "swimming_glass":
        return swimming_glass;
      case "archery_bow_arrow":
        return archery_bow_arrow;
      case "javelin":
        return javelin;
      case "skiing":
        return skiing;
      case "fencing":
        return fencing;
      case "hurdles":
        return hurdles;
      case "skateboarding":
        return skateboarding;
      case "scuba_mouthpiece":
        return scuba_mouthpiece;
      case "running_marathon":
        return running_marathon;
      case "american_football":
        return american_football;
      case "weight_lifting":
        return weight_lifting;
      case "baseball_shot":
        return baseball_shot;
      case "shot_put":
        return shot_put;
      case "skiing2":
        return skiing2;
      case "ice_hockey":
        return ice_hockey;
      case "skating2":
        return skating2;
      case "long_jumping":
        return long_jumping;
      case "snow_skiing":
        return snow_skiing;
      case "golfing":
        return golfing;
      case "mud_riding":
        return mud_riding;
      case "shooting":
        return shooting;
      case "still_rings_gymnastics":
        return still_rings_gymnastics;
      case "paragliding":
        return paragliding;
      case "high_jump":
        return high_jump;
      case "watergliding":
        return watergliding;
      case "water_polo":
        return water_polo;
      case "swimming":
        return swimming;
      case "cycling":
        return cycling;
      case "playing_golf":
        return playing_golf;
      case "pommel_horse_gymnastics":
        return pommel_horse_gymnastics;
      case "pommel_horse_gymnastics2":
        return pommel_horse_gymnastics2;
      case "high_jump2":
        return high_jump2;
      case "floor_exercise_gymnastics":
        return floor_exercise_gymnastics;
      case "river_rafting":
        return river_rafting;
      case "hammer_throw":
        return hammer_throw;
      case "artistic_gymnastics":
        return artistic_gymnastics;
      case "uneven_bars":
        return uneven_bars;
      case "playing_basket_ball":
        return playing_basket_ball;
      case "mountain_climbing":
        return mountain_climbing;
      case "abseiling":
        return abseiling;
      case "diving":
        return diving;
      case "figure_skating":
        return figure_skating;
      case "playing_cricket":
        return playing_cricket;
      case "boxing":
        return boxing;
      case "man_with_olympic_torch":
        return man_with_olympic_torch;
      case "taekwondo":
        return taekwondo;
      case "sports_watch":
        return sports_watch;
      case "boxing_gloves":
        return boxing_gloves;
      case "boxing_stage":
        return boxing_stage;
      case "boxing_tapping":
        return boxing_tapping;
      case "sand_bag":
        return sand_bag;
      case "punching_balls":
        return punching_balls;
      case "boomerang":
        return boomerang;
      case "playing_football":
        return playing_football;
      case "playing_baseball":
        return playing_baseball;
      case "playing_rugby":
        return playing_rugby;
      case "playing_volleyball":
        return playing_volleyball;
      case "sprinting":
        return sprinting;
      case "football_kick":
        return football_kick;
      case "kunfu_kick":
        return kunfu_kick;
      case "playing_tennis":
        return playing_tennis;
      case "cricket_catch":
        return cricket_catch;
      case "beach_volleyball":
        return beach_volleyball;
      case "snow_bowling":
        return snow_bowling;
      case "archery":
        return archery;
      case "basketball2":
        return basketball2;
      case "swimming2":
        return swimming2;
      case "table_tennis2":
        return table_tennis2;
      case "golf":
        return golf;
      case "baseball_ball":
        return baseball_ball;
      case "basketball_ball":
        return basketball_ball;
      case "bowling_ball":
        return bowling_ball;
      case "dumbbell":
        return dumbbell;
      case "football_ball":
        return football_ball;
      case "golf_ball":
        return golf_ball;
      case "hockey_puck":
        return hockey_puck;
      case "quidditch":
        return quidditch;
      case "table_tennis3":
        return table_tennis3;
      case "user_astronaut":
        return user_astronaut;
      default:
        return user_astronaut;
    }
  }
}
